# Generated by Django 5.1.7 on 2025-03-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(blank=True, max_length=200, null=True)),
                ('des', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
