# Generated by Django 5.1.4 on 2025-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_admin_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
